name: Add Daily Flight

on:
  workflow_dispatch:  # Permet l'exécution manuelle

jobs:
  add-flight:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Add today's date
      run: node scripts/add-today-flight.js
    - name: update flight list 
      run: node export-dates.js
      
    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add index.html flights.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Add today's flight date" && git push) 